export const NOTIFICATION_TYPE = {
  STUDENT_ARRIVED: 'STUDENT_ARRIVED',
  STUDENT_LEFT: 'STUDENT_LEFT',
  BUS_BOARDED: 'BUS_BOARDED',
  BUS_DROPPED: 'BUS_DROPPED',
  ETA_UPDATE: 'ETA_UPDATE'
} as const;

export type NotificationType =
  typeof NOTIFICATION_TYPE[keyof typeof NOTIFICATION_TYPE];
